config/routes.rb
DealSite::Application.routes.draw do
  resources :issues do
    resource :import
    resource :publisher
    resources :deal
  end

  resources :import_errors do
    resource :import
  end

  resources :imports do
    resource :publisher
    resources :import_errors
  end

  resources :advertisers do
    resource :publisher
  end

  resources :deals do
    resource :advertiser
  end

  resources :publishers do
    resources :advertisers
    resources :imports
    resources :issues
  end

  match '/' => 'publishers#index', :as => :root
end

app/models/import_error.rb
class ImportError < ActiveRecord::Base
  belongs_to :import
end

app/controllers/import_errors_controller.rb
class ImportErrorsController < ApplicationController
  # GET /import_errors
  # GET /import_errors.json
  def index
    @import = Import.find(params[:import_id])
    @import_errors = @import.import_errors

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @import_errors }
    end
  end

  # GET /import_errors/1
  # GET /import_errors/1.json
  def show
    @import_error = ImportError.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @import_error }
    end
  end

  # GET /import_errors/new
  # GET /import_errors/new.json
  def new
    @import_error = ImportError.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @import_error }
    end
  end

  # GET /import_errors/1/edit
  def edit
    @import_error = ImportError.find(params[:id])
  end

  # POST /import_errors
  # POST /import_errors.json
  def create
    @import_error = ImportError.new(params[:import_error])

    respond_to do |format|
      if @import_error.save
        format.html { redirect_to @import_error, notice: 'Import error was successfully created.' }
        format.json { render json: @import_error, status: :created, location: @import_error }
      else
        format.html { render action: "new" }
        format.json { render json: @import_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /import_errors/1
  # PUT /import_errors/1.json
  def update
    @import_error = ImportError.find(params[:id])

    respond_to do |format|
      if @import_error.update_attributes(params[:import_error])
        format.html { redirect_to @import_error, notice: 'Import error was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @import_error.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /import_errors/1
  # DELETE /import_errors/1.json
  def destroy
    @import_error = ImportError.find(params[:id])
    @import_error.destroy

    respond_to do |format|
      format.html { redirect_to import_errors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/import_errors_helper.rb
module ImportErrorsHelper
end

app/views/import_errors/_form.html.erb
<%= form_for(@import_error) do |f| %>
  <% if @import_error.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import_error.errors.count, "error") %> prohibited this import_error from being saved:</h2>

      <ul>
      <% @import_error.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :error %><br />
    <%= f.text_field :error %>
  </div>
  <div class="field">
    <%= f.label :import_id %><br />
    <%= f.number_field :import_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/import_errors/edit.html.erb
<h1>Editing import_error</h1>

<%= render 'form' %>

<%= link_to 'Show', @import_error %> |
<%= link_to 'Back', import_errors_path %>

app/views/import_errors/index.html.erb
<h1>Listing import_errors</h1>

<table class="publishers table table-striped">
  <tr>
    <th>Data</th>
    <th>Error</th>
    <th>Import</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @import_errors.each do |import_error| %>
  <tr>
    <td><%= import_error.data %></td>
    <td><%= import_error.error %></td>
    <td><%= import_error.import_id %></td>
    <td><%= link_to 'Show', import_error %></td>
    <td><%= link_to 'Edit', edit_import_error_path(import_error) %></td>
    <td><%= link_to 'Destroy', import_error, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Import error', new_import_error_path %>

app/views/import_errors/new.html.erb
<h1>New import_error</h1>

<%= render 'form' %>

<%= link_to 'Back', import_errors_path %>

app/views/import_errors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @import_error.data %>
</p>

<p>
  <b>Error:</b>
  <%= @import_error.error %>
</p>

<p>
  <b>Import:</b>
  <%= @import_error.import_id %>
</p>


<%= link_to 'Edit', edit_import_error_path(@import_error) %> |
<%= link_to 'Back', import_errors_path %>