config/routes.rb
DealSite::Application.routes.draw do
  resources :issues do
    resource :import
    resource :publisher
    resources :deal
  end

  resources :import_errors do
    resource :import
  end

  resources :imports do
    resource :publisher
    resources :import_errors
  end

  resources :advertisers do
    resource :publisher
  end

  resources :deals do
    resource :advertiser
  end

  resources :publishers do
    resources :advertisers
    resources :imports
    resources :issues
  end

  match '/' => 'publishers#index', :as => :root
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  
  has_many   :advertisers
  belongs_to :parent, class_name: "Publisher"
  has_many   :publishers, foreign_key: :parent_id
  has_many   :imports
  has_many :issues
  validates  :name, :uniqueness => true

  validate :parent_is_another_publisher

  def parent_is_another_publisher
    if parent && parent == self
      errors.add :parent, " cannot be self"
    end
    true
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publishers = Publisher.all
  end

  def new
    @publisher = Publisher.new(params[:publisher])
    render :edit
  end

  def create
    @publisher = Publisher.new(params[:publisher])

    if @publisher.save
      redirect_to edit_publisher_path(@publisher), notice: 'Publisher was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    @publisher = Publisher.find(params[:id])
    if @publisher.update_attributes(params[:publisher])
      flash[:notice] = "Updated #{@publisher.name}"
      redirect_to edit_publisher_path(@publisher)
    else
      render :edit
    end
  end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_publisher.html.erb
<tr>
  <td><%= publisher.name %></td>
  <td><%= publisher.theme %></td>
  <td><%= link_to "Advertisers (#{publisher.advertisers.count})", publisher_advertisers_path(publisher) %></td>
  <td><%= link_to "Imports (#{publisher.imports.count})", publisher_imports_path(publisher) %></td>
  <td><%= link_to "Issues (#{publisher.issues.count})", publisher_issues_path(publisher) %></td>
  <td><%= link_to "Edit", edit_publisher_path(publisher) %></td>
</tr>

app/views/publishers/edit.html.erb
<h1>Publisher: <%= @publisher.name %></h1>

<%= form_for(@publisher) do |f| %>
  <label>Name</label>
  <%= f.text_field :name %>

  <label>Theme</label>
  <%= f.text_field :theme %>

  <!-- Moved to Deal? Don't think we still need this. SW: Jun 3, 2008 -->
  <!-- <label>City</label> -->
  <%#= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/publishers/index.html.erb
<h1>Publishers</h1>

<table class="publishers table table-striped">
  <thead>
    <th>Name</th>
    <th>Label</th>
    <th/>
    <th/>
    <th/>
    <th/>
  </thead>
  <tbody>
<%= render @publishers.sort_by(&:name) %>
  </tbody>
</table>

<p>
  <%= link_to "New Publisher", new_publisher_path %>
</p>