config/routes.rb
DealSite::Application.routes.draw do
  resources :issues do
    resource :import
    resource :publisher
    resources :deal
  end

  resources :import_errors do
    resource :import
  end

  resources :imports do
    resource :publisher
    resources :import_errors
  end

  resources :advertisers do
    resource :publisher
  end

  resources :deals do
    resource :advertiser
  end

  resources :publishers do
    resources :advertisers
    resources :imports
    resources :issues
  end

  match '/' => 'publishers#index', :as => :root
end

app/models/import.rb
class Import < ActiveRecord::Base
  belongs_to :publisher
  has_many :import_errors
  has_many :issues
  
  after_initialize :init

  def import(import_data)
    eat_header = true
    headers = ""
    import_data.each_line do |row|
      begin
        if eat_header
          headers = header_row_parser(row)
          eat_header = false
        else
          options = data_row_parser(row, headers)
          advertiser = Advertiser.where(name: options[:name]).first_or_create(name: options.delete(:name), publisher: publisher)
          deal = Deal.new(options.merge(advertiser: advertiser))
          deal.save(validate: false)
          if !deal.valid?
            Issue.create(deal: deal, publisher: publisher, import: self, message: deal.errors.full_messages.join(", "))
          end
        end
      rescue => e
        ImportError.create(data: row, error: e.to_s, import: self)
        logger.error "Errror Importing row: #{row} " + e.to_s
      end
    end
  end
  
  def self.import(publisher_name, import_data)
    # Crate or Get a Publisher
    publisher = Publisher.where(name: publisher_name).first_or_create
    importer = Import.create(publisher: publisher)
    importer.import(import_data)
  end
  
  def init
    self.field_transforms ||=
    "{
      name: ->(x) {x},
      start_at: ->(x) {x},
      end_at: ->(x) {x},
      description: ->(x) {x},
      price: ->(x) {x},
      value: ->(x) {x}
    }"
  
    self.header_transforms ||= 
    {
      "Merchant" => :name,
      "Date" => :start_at,
      "Ends" => :end_at,
      "Deal" => :description,
      "Price" => :price,
      "Value" => :value
    }
    self.header_parse_regex ||= /\s+/
    self.field_parse_regex ||= /(.+)\s(\d+\/\d+\/\d+)\s+(\d+\/\d+\/\d+)\s+(.+)\s+(\d+)\s+(\d+)/
  end
  
  def header_row_parser(header_string)
    header_string.strip.split(header_parse_regex)
  end
  
  def data_row_parser(row_string, headers)
    row = row_string.match(field_parse_regex).captures
    hsh = Hash[headers.zip(row)]
    Hash[hsh.map {|k, v| [header_transforms[k], get_transform(k).call(v.strip)] }]
  end
  
  protected
  
  def get_transform(key)
    e_field_transforms = eval field_transforms
    e_field_transforms[header_transforms[key]]
  end
  
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  # GET /imports
  # GET /imports.json
  def index
    @publisher = Publisher.find(params[:publisher_id])
    @imports = @publisher.imports

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @imports }
    end
  end

  # GET /imports/1
  # GET /imports/1.json
  def show
    @import = Import.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @import }
    end
  end

  # GET /imports/new
  # GET /imports/new.json
  def new
    @publisher = Publisher.find(params[:publisher_id])
    @import = Import.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @import }
    end
  end

  # GET /imports/1/edit
  def edit
    @import = Import.find(params[:id])
  end

  # POST /imports
  # POST /imports.json
  def create
    @publisher = Publisher.find(params[:publisher_id])
    @import = Import.new(params[:import])
    @import.publisher = @publisher

    if @import.save
      redirect_to edit_import_path(@import), notice: 'Import was successfully created.'
    else
      render action: "new"
    end

  end

  # PUT /imports/1
  # PUT /imports/1.json
  def update
    @import = Import.find(params[:id])

    if @import.update_attributes(params[:import])
      redirect_to edit_import_path(@import), notice: 'Import was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /imports/1
  # DELETE /imports/1.json
  def destroy
    @import = Import.find(params[:id])
    @import.destroy

    respond_to do |format|
      format.html { redirect_to imports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/_form.html.erb
<%= form_for([@publisher, @import]) do |f| %>
  <% if @import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% @import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :field_transforms %><br />
    <%= f.text_field :field_transforms %>
  </div>

  <div class="field">
    <%= f.label :header_transforms %><br />
    <%= f.text_field :header_transforms %>
  </div>

  <div class="field">
    <%= f.label :header_parse_regex %><br />
    <%= f.text_field :header_parse_regex %>
  </div>

  <div class="field">
    <%= f.label :field_parse_regex %><br />
    <%= f.text_field :field_parse_regex %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<h1>Editing import</h1>

<%= render 'form' %>

app/views/imports/index.html.erb
<h1>Listing imports</h1>

<table class="publishers table table-striped">
  <tr>
    <th>Publisher</th>
	<th>Errors</th>
    <th></th>
    <th></th>
  </tr>

<% @imports.each do |import| %>
  <tr>
    <td><%= import.publisher_id %></td>
	<td><%= link_to "Errors (#{import.errors.size})", import_import_errors_path(import) %></td>
    <td><%= link_to 'Edit', edit_import_path(import) %></td>
    <td><%= link_to 'Destroy', import, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Import', new_publisher_import_path(@publisher) %>

app/views/imports/new.html.erb
<h1>New import</h1>

<%= render 'form' %>